### PR TITLE
just some minor changes to make it easier to start up

### PR DESCRIPTION
**Pull request by dankolbrs**
Glad to find this, I was getting ready to build my own! Saw this project when checking out the show notes from [hamradio360](http://hamradio360.com/index.php/2016/08/02/ham-radio-workbench-3-power-supplies/).

### CODE REVIEW

**Comment by ScottChapman** [comment]
I actually like the idea of optionally sleeping on startup (it only seems useful for waiting for the desktop to be up and running). Or maybe there is a better mechanism to know that the desktop is up and running...

**Comment by dankolbrs** [comment]
I was thinking about that too. The commit removing/re-adding was because I took out the sleep to test the startup script on an already running desktop.

A `-n` or `--no-sleep`flag when running manually to disable sleep could be a good way to go.

**Comment by n0bel** [comment]
I like your changes to startup.sh...

The changes to config-example, i'd not do, because people put different centers and different markers onto different radar blocks, and that change makes it less obvious that such a thing can be done.  

Otherwise I would have written the radar blocks as just a location and a zoom factor, and do everything else in the code.

There should be a way to tell if the desktop is up and running..  Alternatively I should have probably made it run from the desktop's autorun capability.  Ideally such a check would see if the whole desktop was up and running rather than just the xserver. 

/K

**Comment by ScottChapman** [comment]
I actually like the idea of making it easy for all the locations to be the same (I would assume that would be an appropriate default config and suspect it would be the most common). I think you can simple comment the code so that it is clear how to change it from the default. 

Just my $0.02 (rounding up)

**Comment by dankolbrs** [comment]
Thanks @n0bel , understandable. I do think that it would be beneficial for something to make it easier in the first setup so that the lat/lon only needs to be entered once if other locations/views aren't wanted right away.

How do you feel about something like:
```python
# LOCATION(S) 
# Further radar configuration (zoom, marker location) can be completed under the RADAR section
primary_location = 44.9764016,-93.2486732 # Change to your Lat/Lon
# other location centers can be entered below, otherwise primmary location will be used
radar_center1 = ""
radar_center2 = ""
radar_center3 = ""
radar_center4 = ""
```

This could be parsed, and use the primary_location if no other centers are used. Also, it points to more advanced configuration that could be entered in the JSON blobs if desired. This may be a bit much, especially since markers/satellite/zoom wall would still require changes directly in the JSON.

Or, maybe just using `pirmary_location` in the radar JSON sections could make it more clear that it will reuse the same location and marker for each radar screen. It will still save initial configuration, and anyone that wants to change it will have to change them all anyway.

**Comment by n0bel** [comment]
I think the best choice will be to use your Config-example.py as you've done it in the commit.   And then have Config-Example-Advanced.py as another example to copy from.

**Comment by ScottChapman** [comment]
Like it.

**Comment by dankolbrs** [comment]
Sorry for the extra commit, I switched up which computer I was editing on

**Comment by n0bel** [comment]
I'd say it's good to go.

**Pull request merged**
