### PR TITLE
Background Slideshow

### PR DESCRIPTION
**Pull request by togatown**
Please feel free to criticize! Although I have some code writing background, I have no previous knowledge of Python.

Things to do:

- Go to previous image or next image
- Control Keys previous image, next image
- Transitions, fades or animations from one screen to another
- Add light sensor to stop slideshow at night

EDIT:
Done:
- Turn off foreground, toggle the clock, forecast, etc off to view SS uninhibited.
- Control Keys, F8 pause, F9 toggle foreground
- Monitor changes to the images folder

### CODE REVIEW

**Comment by n0bel** [comment]
Thanks @togatown 
I want to run this version myself for a while before I merge it.   I've not had a chance to pull it.   I also want to be sure it passes PEP8.

**Comment by togatown** [comment]
@n0bel Might be a little early. I'm still working on it. Life got in the way and I haven't touched it since Sunday I believe.....

**Comment by togatown** [comment]
@n0bel Had a few minutes tonight so I cleaned this up. Used pep8online.com to check the file and only have a few slightly long lines. Seems to work reasonably well.

The second hand does jump a little when loading images. Any advice?

F6-F7 Previous-Next Image
F8 Pause
F9 Toggle foreground

**Comment by togatown** [comment]
> In the Config-*.py `True` and `False` are not used.
> For users without a python background it may not be clear that `true` is invalid.
> I assume @n0bel therefor used '0' and '1'

@BertLindeman makes sense, not every one would know that it is case sensitive. Noted and changed in the config.

**Comment by n0bel** [comment]
Thank you!

**Pull request merged**
