### PR TITLE
Change from Google Maps to Mapbox maps to display roads/borders over weather radar

### PR DESCRIPTION
**Pull request by SerBrynden**
Regarding Issue  #81:  Made changes to PiClock so that it uses customized maps from Mapbox (OpenStreetMap) instead of Google Maps.  In doing so, utilized a bottom map layer of land and water only, then the weather radar layer, and then a top transparent layer of labels, roads, borders, and markers only.  I created the map layers myself, using the free [Mapbox Studio](https://www.mapbox.com/mapbox-studio/).  Further details and tweaks listed in the commit descriptions.

Known Issue: 
Timestamp for animated weather radar can be partially obscured by the Mapbox overlay layer (labels, roads, borders).  No easy method for creating additional Weather Underground layer to go on top with hidden radar but visible timestamp.

### CODE REVIEW

**Comment by dankolbrs** [comment]
I do like the idea of having a different map provider, the opacity issue this is solving, and especially like a lot of the clean ups that come along with this...  but... I think this is too much change in a PR. The biggest issue I see with this is that it breaks the [upgrade approach](https://github.com/n0bel/PiClock/blob/master/Documentation/Install.md#updating-to-newerupdated-versions). Merging this on an existing installation requires:
* Obtaining a mapbox API key
* Manually merging changes in Config.py
* Manually merging changes in ApiKeys.py

This would fit in well with the modularization/plugin approach in #77 and overall [PiClock²](https://github.com/n0bel/PiClock/projects/1), but this would need changes to allow the choice of either GoogleMaps or MapBox based on the config. It looks like it should be fairly trivial but I'm not sure if some Config-Example.py changes are based on preference or requirement with the change in the map provider.

Great to see someone else throwing code at @n0bel !

**Comment by SerBrynden** [comment]
Understood.  I'll look into making the choice between Google Map vs. Mapbox user selectable and/or modularized. By the way, is the update feature for future use?  Because the only code in update.py is 
`print "Nothing to do."`

**Comment by dankolbrs** [comment]
Sorry for the confusion there, I probably could have elaborated more. Currently updating is effectively just a pull of master from github. I can't speak for @n0bel , but I *think* the idea of the update.py was to have a method to programmatically handle breaking changes or issues in update. But, in the year or so I've been posting my opinion on this repo all the changes have been pretty conservative and not needed any extra work in update.py. By the upgrade instructions being as they are, and update.py not doing anything, the flow is still accurate even though running update.py is unnecessary.

There was some discussion of updates in #54 (just a couple mentions of it, probably a few other mentions buried in other issues). Also configuration file changes were discussed to determine a method of programmatically making changes to the configuration during an update. The goal is to move to PiClock2 rather than iterate or make large feature changes on the existing version.

We seemed to have lost steam when summer hit. I'd recommend taking a look at the existing issues and the project I linked in the previous comment for an idea of the direction this was trying to go (which changing the map provider fits in). 

And just to make sure it's clear, I don't have a commit bit to this repo. This is all based on my involvement with this project as a contributor and ultimately @n0bel is the Torvalds of PiClock (meant entirely complimentary).

**Comment by n0bel** [comment]
@dankolbrs we always seem to be on the same page!

**Comment by n0bel** [comment]
> We seemed to have lost steam when summer hit
Yup sure did..  between bike riding season and a purchase of a 3d printer (and corresponding fun learning/time sink) PiClock has been sitting on the back burner.

**Comment by n0bel** [comment]
@SerBrynden @dankolbrs I'm going to leave this pull request open, as a reference for things to do in PiClock² Ultimately I'll reject it once implemented in PiClock.

**Comment by SerBrynden** [comment]
No worries.  And yes, please take a look at my commits, as there are some minor improvements that should be easy to implement right away.  Let me know if I can help or if you have any questions about why I did something a certain way.  I probably didn't leave as many comments in the code as I should have.  Thank you!

**Comment by n0bel** [comment]
Mapbox is being implemented in a slightly different way.   This code was reviewed and helped in the process.

**Pull request closed without merging**
