### PR TITLE
Adds caching for weather and radar images.

### PR DESCRIPTION
**Pull request by dankolbrs**
Caches weather and radar calls, verifies cache prior to performing
API calls to lower API call volume for application restarts or
frame switches.

Also updates library import in Config-Example to use PyQt5
(got me when testing).

### CODE REVIEW

**Comment by n0bel** [comment]
Perfect..  After reviewing the code, its just like I would have done it.. including -1 minute..   There is some code that tries to limit requests on screen switching.   I'll visit this again and remove that, since I'd rather rely on the new cache.

**Comment by n0bel** [comment]
Thanks Dan!

**Comment by dankolbrs** [comment]
Cool. I probably should have noted this to make sure to point it out, but there is a bit of an issue if someone is testing the application and alters the config such as with a different location. That would result in displaying the stale cached images and throw off the user as nothing is checked other than the filename and mtime. Easy workaround of delete the `.cache` directory.

I started adding dumping the config to cache, and then checking that on application startup. If the config cache changes, then just remove the cache files (or those that changed). Being the `dev` branch, and the intention to move to yaml, I figured that is probably better suited after the config file changes.

**Comment by n0bel** [comment]
Yes, I had already thought of that.   My thought was to hash the url and that becomes part of the file name or cache handle.

Lets wait on config handling changes until yaml is in place.   I believe I have a good structure in mind.

**Pull request merged**
